# Mouse
set -g mouse on

# Prefix - C-b is not acceptable, Vim uses it
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key a send-prefix

# Start window/pane numbering at 1
set -g base-index 1

# Pane titles
set -g pane-border-format '#{pane_index} #{pane_current_command} #(basename "#{pane_current_path}" | sed -E "s/\.Presentation\././; s/\./ /g")'
# set -g pane-border-format '#{pane_index} #(tty="#{pane_tty}"; pgid=$(ps -t "$tty" -o tpgid= | awk '\''NR==1 {print $1}'\''); cmd=$(ps -o comm= -p "$pgid"); if [ "$cmd" = make ]; then ps -o args= -p "$pgid"; else printf "%s" "#{pane_current_command}"; fi) #(basename "#{pane_current_path}" | sed -E "s/\.Presentation\././; s/\./ /g")'

# Allow passthrough for things like shift enter
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Move to pane with ctrl h/j/k/l, but pass the key through to vim/claude
# when the active pane is running one of them (so their own bindings work)
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h  if-shell  "$is_vim"  "send-keys C-h"  "select-pane -L"
bind-key -n C-k  if-shell  "$is_vim"  "send-keys C-k"  "select-pane -U"
bind-key -n C-l   if-shell  "$is_vim"  "send-keys C-l"   "select-pane -R"
bind-key -n C-\   if-shell  "$is_vim"  "send-keys C-\\"  "select-pane -l"

is_vim_or_claude="ps -o state= -o comm= -o args= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ .*(([gn]?vim|view)(diff)?|claude)'"
bind-key -n C-j if-shell "$is_vim_or_claude" "send-keys C-j" "select-pane -D"

# Split windows
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Zoom - toggle pane fullscreen
bind z resize-pane -Z

# Reduce keystroke delay / allow faster key repetition
set -s escape-time 00

# Shell
set-option -g default-shell /opt/homebrew/bin/bash

# Copy mode - vi keys
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'V' send -X select-line
bind-key -T copy-mode-vi Escape send -X cancel
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi WheelUpPane send -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send -X scroll-down

# Copy the entire pane history to the macOS clipboard
bind-key C-c run-shell "tmux capture-pane -p -S - | pbcopy"

# Same action with a shorter key
bind-key y run-shell "tmux capture-pane -p -S - | pbcopy"

# source "$HOME/.local/share/blesh/ble.sh"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
